/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChatId = IDL.Text;
export const Timestamp = IDL.Int;
export const Chat = IDL.Record({
  'id' : ChatId,
  'title' : IDL.Text,
  'messagesJson' : IDL.Text,
  'platform' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ChatSummary = IDL.Record({
  'id' : ChatId,
  'title' : IDL.Text,
  'platform' : IDL.Text,
  'timestamp' : Timestamp,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'deleteChat' : IDL.Func([IDL.Text], [], []),
  'fetchChatPage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getChat' : IDL.Func([IDL.Text], [Chat], ['query']),
  'listChats' : IDL.Func([], [IDL.Vec(ChatSummary)], ['query']),
  'saveChat' : IDL.Func([ChatId, IDL.Text, IDL.Text, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChatId = IDL.Text;
  const Timestamp = IDL.Int;
  const Chat = IDL.Record({
    'id' : ChatId,
    'title' : IDL.Text,
    'messagesJson' : IDL.Text,
    'platform' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ChatSummary = IDL.Record({
    'id' : ChatId,
    'title' : IDL.Text,
    'platform' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'deleteChat' : IDL.Func([IDL.Text], [], []),
    'fetchChatPage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getChat' : IDL.Func([IDL.Text], [Chat], ['query']),
    'listChats' : IDL.Func([], [IDL.Vec(ChatSummary)], ['query']),
    'saveChat' : IDL.Func([ChatId, IDL.Text, IDL.Text, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };